source 'https://rubygems.org'

gem 'rails', '4.2.5.1'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem "celluloid", require: "celluloid/current"

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem "quiet_assets"
end

gem "utter_events", path: "../", require: "utter"

gem "aws-sdk", "~> 2"
